version: '3'

services:
  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    ports:
      - "8080:8080"

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  monolithic:
    build:
      context: .
      dockerfile: Dockerfile.monolithic
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - nats

  query:
    build:
      context: .
      dockerfile: Dockerfile.query
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis
      - nats

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - postgres
      - redis
      - nats

  bff:
    build:
      context: .
      dockerfile: Dockerfile.bff
    ports:
      - "3001:3001"
    depends_on:
      - nats
      - query


volumes:
  postgres_data:
